# Generated by Django 3.0.2 on 2020-03-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourists',
            name='arrival_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourists',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourists',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
